#!/bin/bash

hostname=`hostname`
RABBITMQ_NODENAME=${RABBITMQ_NODENAME:-rabbit}

if [ -z "$CLUSTER_WITH" -o "$CLUSTER_WITH" = "$hostname" ]; then
  echo "Running as single server"
  rabbitmq-server
else
  echo "Running as clustered server"
  #if [ -f /var/.CLUSTERED ] ; then
  #/usr/sbin/rabbitmq-server
  #else
      #touch /var/.CLUSTERED
      rabbitmq-server &
      rabbitmqctl wait $HOME/mnesia/$RABBITMQ_NODENAME@$HOSTNAME.pid
      rabbitmqctl stop_app
      rabbitmqctl join_cluster $RABBITMQ_NODENAME@$CLUSTER_WITH
      rabbitmqctl start_app
      fg
  #fi
  #rabbitmq-server -detached
  #rabbitmqctl status
  #sleep 15
  #rabbitmqctl status
  #rabbitmqctl stop_app

  #echo "Joining cluster $CLUSTER_WITH"
  #rabbitmqctl join_cluster ${ENABLE_RAM:+--ram} $RABBITMQ_NODENAME@$CLUSTER_WITH

  #rabbitmqctl start_app

  # Tail to keep the a foreground process active..
  #tail -f /var/log/rabbitmq/*
fi
